spring:
  application:
    name: ecom-gateway-microservice
  config:
    import: configserver:${CONFIG_SERVER_URL}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://ecom-product-microservice
              predicates:
                - Path=/api/products/**
            - id: user-service
              uri: lb://ecom-user-microservice
              predicates:
                - Path=/api/users/**
            - id: order-service
              uri: lb://ecom-order-microservice
              predicates:
                - Path=/api/orders/**, /api/cart/**

server:
  port: 8080
