spring:
  application:
    name: ecom-user-microservice
  data:
    mongodb:
      uri: mongodb+srv://adriencournand_db_user:2Tpx4mLd3sc9IEp2@ecoms.ffjuyhc.mongodb.net/?appName=ecoms
      database: ecom

server:
  port: 8082
