spring:
  application:
    name: ecom-user-microservice
  profiles:
    active: dev
  config:
    import: configserver:${CONFIG_SERVER_URL}

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
