spring:
  application:
    name: ecom-user-microservice
  datasource:
    url: "jdbc:postgresql://localhost:5432/users"
    username: formation
    password: formation
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
