spring:
  application:
    name: ecom-product-microservice
  datasource:
    url: "jdbc:postgresql://ep-red-pine-abxeouo5-pooler.eu-west-2.aws.neon.tech/products?sslmode=require&channel_binding=require"
    username: neondb_owner
    password: npg_RaKBXcEx9wH1
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
