eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/${spring.application.name}.log
