spring:
  application:
    name: notification
  rabbitmq:
    host: "${RABBITMQ_HOST}"
    port: "${RABBITMQ_PORT}"
    username: "${RABBITMQ_USER}"
    password: "${RABBITMQ_PASS}"
    virtual-host: "${RABBITMQ_VHOST}"
    connection-timeout: 3000

rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking

server:
  port: 8084
