spring:
  application:
    name: ecom-order-microservice
  config:
# TODO: Is it possible to write http://configserver here and let Spring Boot discover the address of the config server at boot time ?
    import: configserver:${CONFIG_SERVER_URL}
  profiles:
    active: dev

server:
  port: 8083
