name: ecom
services:
  rabbitmq:
    container_name: rabbitmq_container
    hostname: rabbitmq-container
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - database
    restart: unless-stopped
  postgres:
    container_name: postgres_container
    hostname: postgres-server
    image: postgres:14
    environment:
      POSTGRES_USER: formation
      POSTGRES_PASSWORD: formation
      PGDATA: /databases/postgres
    ports:
      - "5432:5432"
    networks:
      - database
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: adrien.cournand@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - database
    restart: unless-stopped
  mongodb:
    container_name: mongodb_server
    hostname: mongodb-server
    image: mongodb/mongodb-community-server
    ports:
      - "27017:27017"
    networks:
      - database
    restart: unless-stopped
  zeikin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - database

networks:
  database:
    driver: bridge

volumes:
  pgadmin:
